module.exports=[{
    "id":31,
    "urlSlug":"anshika-saxena",
    "namePrefix":null,
    "firstName":"anshika",
    "lastName":"saxena",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       "english","hindi"
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
        "vastu","palmistry"
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 },
 {
    "id":32,
    "urlSlug":"varu",
    "namePrefix":null,
    "firstName":"Varun",
    "lastName":"Kumar",
    "aboutMe":"Hello I am here",
    "profliePicUrl":null,
    "experience":1.0,
    "languages":[
       "english","hindi","marathi"
    ],
    "minimumCallDuration":5,
    "minimumCallDurationCharges":50.0,
    "additionalPerMinuteCharges":10.0,
    "isAvailable":true,
    "rating":null,
    "skills":[
        "vastu","palmistry"
    ],
    "isOnCall":false,
    "images":{
       "large":{
          "imageUrl":"",
          "id":92
       },
       "medium":{
          "imageUrl":"https://tak-astrotak-av-dev.s3.ap-south-1.amazonaws.com/astro-images/agents/1.png",
          "id":123
       }
    },
    "availability":{
       "days":[
          "MON",
          "WED",
          "THU",
          "FRI"
       ],
       "slot":{
          "toFormat":"PM",
          "fromFormat":"AM",
          "from":"10",
          "to":"7"
       }
    }
 }]